package com.github.maximtereshchenko.games.cookies.domain;

public enum Achievement {

    CUMULATIVE_BAKED_TIER_0,
    CUMULATIVE_BAKED_TIER_1,
    CUMULATIVE_BAKED_TIER_2,
    CUMULATIVE_BAKED_TIER_3,
    CUMULATIVE_BAKED_TIER_4,
    CUMULATIVE_BAKED_TIER_5,
    CUMULATIVE_BAKED_TIER_6,
    CUMULATIVE_BAKED_TIER_7,
    CUMULATIVE_BAKED_TIER_8,
    CUMULATIVE_BAKED_TIER_9,
    CUMULATIVE_BAKED_TIER_10,
    CUMULATIVE_BAKED_TIER_11,
    CUMULATIVE_BAKED_TIER_12
}
