screens.main.title=BRICKS
screens.main.buttons.play=Play
screens.main.buttons.settings=Settings
screens.difficulties.buttons.easy.name=Easy
screens.difficulties.buttons.dense.name=Dense
screens.difficulties.buttons.hard.name=Hard
screens.difficulties.buttons.superHard.name=Super hard
