preferences.name=com.github.maximtereshchenko.games.snakes.Snakes
world.width=35
world.height=18
interface.viewport.height=720
snake.food.growth=3
snake.head.x=11
snake.head.y=6
snake.head.movement.forward.direction=RIGHT
snake.length=3
assets.skin=skin.json
assets.font.name=default.fnt
assets.font.atlas.name=skin.atlas
assets.bundle.loading=loading
assets.bundle.game=game
assets.music=music.mp3
music.volume.default=0.1
modes=classic,viper,sidewinder
modes.classic.unlock.requirements.profile.LAUNCHES=0
modes.classic.snake.head.movement.turns.legal=SAME,LEFT,RIGHT
modes.classic.snake.head.movement.sideways.cycle=0
modes.classic.snake.head.movement.sideways.interval=0
modes.classic.snake.head.warp.edge=OPPOSITE
modes.classic.game.interval=0.125
modes.classic.palette.BACKGROUND=ded4baff
modes.classic.palette.HEAD=33824dff
modes.classic.palette.SEGMENT=66ce81ff
modes.classic.palette.FOOD=33824dff
modes.classic.palette.FOOD_EATEN_COUNTER=454248ff
modes.classic.palette.WARP=64b6b0ff
modes.viper.unlock.requirements.session.LEFT_TURNS=20
modes.viper.snake.head.movement.turns.legal=RIGHT
modes.viper.snake.head.movement.sideways.cycle=0
modes.viper.snake.head.movement.sideways.interval=0
modes.viper.snake.head.warp.edge=OPPOSITE
modes.viper.game.interval=0.125
modes.viper.palette.BACKGROUND=eeeeddff
modes.viper.palette.HEAD=774422ff
modes.viper.palette.SEGMENT=ddaa88ff
modes.viper.palette.FOOD=774422ff
modes.viper.palette.FOOD_EATEN_COUNTER=175ca5ff
modes.viper.palette.WARP=aa9a99ff
modes.sidewinder.unlock.requirements.profile.CREDITS_READ=1
modes.sidewinder.snake.head.movement.turns.legal=SAME,LEFT,RIGHT
modes.sidewinder.snake.head.movement.sideways.cycle=2
modes.sidewinder.snake.head.movement.sideways.interval=7
modes.sidewinder.snake.head.warp.edge=OPPOSITE
modes.sidewinder.game.interval=0.125
modes.sidewinder.palette.BACKGROUND=ffeeefff
modes.sidewinder.palette.HEAD=452210ff
modes.sidewinder.palette.SEGMENT=885633ff
modes.sidewinder.palette.FOOD=452210ff
modes.sidewinder.palette.FOOD_EATEN_COUNTER=000000ff
modes.sidewinder.palette.WARP=000000ff
