preferences.name=com.github.maximtereshchenko.games.snake.Snakes
world.width=33
world.height=16
interface.viewport.height=720
snake.food.growth=3
snake.head.x=11
snake.head.y=6
snake.head.direction=RIGHT
snake.length=3
assets.skin=skin.json
assets.font.name=default.fnt
assets.font.atlas.name=skin.atlas
assets.bundle.loading=loading
assets.bundle.game=game
modes=classic,viper
modes.classic.unlock.requirements.profile.LAUNCHES=1
modes.classic.snake.turns.legal=LEFT,RIGHT
modes.classic.game.interval=0.125
modes.classic.palette.BACKGROUND=ded4baff
modes.classic.palette.HEAD=33824dff
modes.classic.palette.SEGMENT=66ce81ff
modes.classic.palette.FOOD=33824dff
modes.classic.palette.FOOD_EATEN_COUNTER=454248ff
modes.viper.unlock.requirements.session.LEFT_TURNS=20
modes.viper.snake.turns.legal=RIGHT
modes.viper.game.interval=0.125
modes.viper.palette.BACKGROUND=eeeeddff
modes.viper.palette.HEAD=774422ff
modes.viper.palette.SEGMENT=ddaa88ff
modes.viper.palette.FOOD=774422ff
modes.viper.palette.FOOD_EATEN_COUNTER=175ca5ff
