screens.title.text=SNAKES\n\
Press any key to continue
screens.main.buttons.statistics.name=Statistics
screens.main.buttons.statistics.description=Check out all your game statistics in here.
screens.main.buttons.credits.name=Credits
screens.main.buttons.credits.description=This is the credits screen.
screens.main.buttons.settings.name=Settings
screens.main.buttons.settings.description=This is the settings screen.
screens.main.buttons.modes.classic.name=Classic
screens.main.buttons.modes.classic.description=This is the basic snake game.
screens.main.buttons.modes.viper.name=Viper
screens.main.buttons.modes.viper.description=Vipers are the Derek Zoolanders of the snake kingdom.
screens.main.buttons.modes.viper.unlock.requirement=Make 20 left turns in one run.
screens.main.buttons.modes.sidewinder.name=Sidewinder
screens.main.buttons.modes.sidewinder.description=Sidewinders come at all problems in life from strange angles.
screens.main.buttons.modes.sidewinder.unlock.requirement=Read the credits.
screens.main.buttons.modes.sea.name=Sea snake
screens.main.buttons.modes.sea.description=Sea snakes are really good at holding their breath, but they can't do it indefinitely.
screens.main.buttons.modes.sea.unlock.requirement=Unlock a quarter of the snake levels.
screens.main.buttons.modes.hognose.name=Hognose
screens.main.buttons.modes.hognose.description=Despite it's appearance, Hognose snakes have quite the big mouth.
screens.main.buttons.modes.hognose.unlock.requirement=Die with exactly one point.
screens.main.buttons.modes.mamushi.name=Mamushi
screens.main.buttons.modes.mamushi.description=Mamushis never think things through and have a bad habit of leaving enemies in their wake as a result.
screens.main.buttons.modes.mamushi.unlock.requirement=Eat an odd number of pills in one session.
screens.session.air.template=AIR: {0}
screens.session.food.consumed.template={0}
screens.statistics.LAUNCHES=Game launches
screens.statistics.CREDITS_READ=Credits read
screens.statistics.MODES_UNLOCKED=Modes unlocked
screens.statistics.buttons.back=Back
screens.settings.buttons.back=Back
screens.settings.sliders.music.volume=Music volume
screens.credits.text=Snakes\n\n\
  Maxim Tereshchenko\n\
  https://github.com/maximtereshchenko\n\n\
  Original idea:\n\
  Snakes On a Cartesian Plane\n\
  by Cale Bradbury (@netgrind)\n\
  https://www.kongregate.com/en/games/netgrind/snakes-on-a-cartesian-plane
screens.credits.buttons.back=Back
