title.name=SNAKES
title.continue=Press SPACE
modeSelection.statistics.name=Statistics
modeSelection.statistics.description=Check out all your game statistics in here.
modeSelection.credits.name=Credits
modeSelection.credits.description=This is the credits screen.
modeSelection.settings.name=Settings
modeSelection.settings.description=This is the settings screen.
statistics.LAUNCHES=Game launches
statistics.back=Back
settings.back=Back
settings.music.volume=Music volume
credits.text=Snakes\n\
Maxim Tereshchenko\n\
https://github.com/maximtereshchenko
credits.back=Back
mode.classic.name=Classic
mode.classic.description=This is the basic snake game.
mode.viper.name=Viper
mode.viper.description=Vipers are the Derek Zoolanders of the snake kingdom.
mode.viper.requirement=Make 20 left turns in one run.
