screens.title.text=SNAKES\n\
Press any key to continue
screens.main.buttons.statistics.name=Statistics
screens.main.buttons.statistics.description=Check out all your game statistics in here.
screens.main.buttons.credits.name=Credits
screens.main.buttons.credits.description=This is the credits screen.
screens.main.buttons.settings.name=Settings
screens.main.buttons.settings.description=This is the settings screen.
screens.statistics.LAUNCHES=Game launches
screens.statistics.buttons.back=Back
screens.settings.buttons.back=Back
screens.settings.sliders.music.volume=Music volume
screens.credits.text=Snakes\n\n\
  Maxim Tereshchenko\n\
  https://github.com/maximtereshchenko\n\n\
  Original idea:\n\
  Snakes On a Cartesian Plane\n\
  by Cale Bradbury (@netgrind)\n\
  https://www.kongregate.com/en/games/netgrind/snakes-on-a-cartesian-plane
screens.credits.buttons.back=Back
modes.classic.name=Classic
modes.classic.description=This is the basic snake game.
modes.viper.name=Viper
modes.viper.description=Vipers are the Derek Zoolanders of the snake kingdom.
modes.viper.unlock.requirement=Make 20 left turns in one run.
