cookies=cookies
bakingRate=per second: {0}
store=Store
upgrades=Upgrades
buildings=Buildings
buildings.names.locked=???
buildings.names.CURSOR=Cursor
buildings.counts.button.zero=
buildings.counts.button={0}
buildings.counts.tooltip.zero=Owned: {0}
buildings.counts.tooltip=Owned: {0}
buildings.flavorTexts.locked="???"
buildings.flavorTexts.CURSOR="Autoclicks once every 10 seconds."
upgrade=Upgrade
upgrades.names.CURSOR_TIER_0=Reinforced index finger
upgrades.names.CURSOR_TIER_1=Carpal tunnel prevention cream
upgrades.names.CURSOR_TIER_2=Ambidextrous
upgrades.names.CURSOR_TIER_3=Thousand fingers
upgrades.names.CURSOR_TIER_4=Million fingers
upgrades.names.CURSOR_TIER_5=Billion fingers
