cookies=cookies
bakingRate=per second: {0}
store=Store
upgrades=Upgrades
buildings=Buildings
buildings.names.locked=???
buildings.names.CURSOR=Cursor
buildings.names.GRANDMA=Grandma
buildings.counts.button.zero=
buildings.counts.button={0}
buildings.counts.tooltip.zero=Owned: {0}
buildings.counts.tooltip=Owned: {0}
buildings.flavorTexts.locked="???"
buildings.flavorTexts.CURSOR="Autoclicks once every 10 seconds."
buildings.flavorTexts.GRANDMA="A nice grandma to bake more cookies."
upgrade=Upgrade
upgrades.names.CURSOR_TIER_0=Reinforced index finger
upgrades.names.CURSOR_TIER_1=Carpal tunnel prevention cream
upgrades.names.CURSOR_TIER_2=Ambidextrous
upgrades.names.CURSOR_TIER_3=Thousand fingers
upgrades.names.CURSOR_TIER_4=Million fingers
upgrades.names.CURSOR_TIER_5=Billion fingers
upgrades.names.GRANDMA_TIER_0=Forwards from grandma
upgrades.names.GRANDMA_TIER_1=Steel-plated rolling pins
upgrades.names.GRANDMA_TIER_2=Lubricated dentures
upgrades.names.GRANDMA_TIER_3=Prune juice
upgrades.names.GRANDMA_TIER_4=Double-thick glasses
upgrades.names.GRANDMA_TIER_5=Aging agents
upgrades.descriptions.CURSOR_TIER_0=The mouse and cursors are twice as efficient.
upgrades.descriptions.CURSOR_TIER_1=The mouse and cursors are twice as efficient.
upgrades.descriptions.CURSOR_TIER_2=The mouse and cursors are twice as efficient.
upgrades.descriptions.CURSOR_TIER_3=The mouse and cursors gain +0.1 cookies for each non-cursor object owned.
upgrades.descriptions.CURSOR_TIER_4=Multiplies the gain from Thousand fingers by 5.
upgrades.descriptions.CURSOR_TIER_5=Multiplies the gain from Thousand fingers by 10.
upgrades.descriptions.GRANDMA_TIER_0=Grandmas are twice as efficient.
upgrades.descriptions.GRANDMA_TIER_1=Grandmas are twice as efficient.
upgrades.descriptions.GRANDMA_TIER_2=Grandmas are twice as efficient.
upgrades.descriptions.GRANDMA_TIER_3=Grandmas are twice as efficient.
upgrades.descriptions.GRANDMA_TIER_4=Grandmas are twice as efficient.
upgrades.descriptions.GRANDMA_TIER_5=Grandmas are twice as efficient.
upgrades.flavorTexts.CURSOR_TIER_0="prod prod"
upgrades.flavorTexts.CURSOR_TIER_1="it... it hurts to click..."
upgrades.flavorTexts.CURSOR_TIER_2="Look ma, both hands!"
upgrades.flavorTexts.CURSOR_TIER_3="clickity"
upgrades.flavorTexts.CURSOR_TIER_4="clickityclickity"
upgrades.flavorTexts.CURSOR_TIER_5="clickityclickityclickity"
upgrades.flavorTexts.GRANDMA_TIER_0="RE:RE:thought you'd get a kick out of this ;))"
upgrades.flavorTexts.GRANDMA_TIER_1="Just what you kneaded."
upgrades.flavorTexts.GRANDMA_TIER_2="squish"
upgrades.flavorTexts.GRANDMA_TIER_3="Gets me going."
upgrades.flavorTexts.GRANDMA_TIER_4="Oh... so THAT's what I've been baking."
upgrades.flavorTexts.GRANDMA_TIER_5="Counter-intuitively, grandmas have the uncanny ability to become more powerful the older they get."
upgrades.tooltips.clickToPurchase=Click to purchase.
