views.bakery.panels.bakery.labels.cookies=cookies
views.bakery.panels.bakery.labels.bakingRate=per second: {0}
views.bakery.panels.store.labels.name=Store
views.bakery.panels.store.labels.upgrades=Upgrades
views.bakery.panels.store.labels.buildings=Buildings
views.bakery.buildings.locked.name=???
views.bakery.buildings.CURSOR.name=Cursor
